name: Python package

on: [push]

jobs:
  maya_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:

      # Without this, all containers stop if any fail
      # That's bad, we want to know whether it's only one
      # or if it happens to multiples or all.
      fail-fast: false

      matrix:
        include:
          - maya: "2023"
            pip: "get-pip.py"
          - maya: "2024"
            pip: "get-pip.py"
          - maya: "2025"
            pip: "get-pip.py"

    container: mottosso/maya:${{ matrix.maya }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    # We'll lock each version to one that works with both Python 2.7 and 3.7
    - name: pip install
      run: |
        wget https://bootstrap.pypa.io/pip/${{ matrix.pip }}
        mayapy get-pip.py --user
        mayapy -m pip install --user \
          nose==1.3.7 \
          nose-exclude==0.5.0 \
          coverage==5.5 \
          flaky==3.7.0 \
          sphinx==1.8.5 \
          sphinxcontrib-napoleon==0.7 \
          qtpy

    - name: Environment
      run: |
        export XDG_RUNTIME_DIR=/var/tmp/runtime-root
        export MAYA_DISABLE_ADP=1
    - name: Unittests
      run: |
        pwd
        ls
        mayapy --version
        mayapy -m unittest
